apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-airflow
  namespace: monitoring
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          metadata:
            labels:
              app: restart-airflow        
          restartPolicy: Never
          serviceAccountName: deployment-edit-sa
          containers:
          - name: restart-airflow
            image: europe-north1-docker.pkg.dev/knada-gcp/knada-north/knada-restart-scheduler
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-edit-sa
  namespace: monitoring
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-edit-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-edit-binding
subjects:
  - kind: ServiceAccount
    name: deployment-edit-sa
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: deployment-edit-role
  apiGroup: rbac.authorization.k8s.io
---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-api-server
  namespace: monitoring
spec:
  podSelector:
      matchLabels:
        app: restart-airflow
  policyTypes:
  - Egress
