apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-airflow
  namespace: monitoring
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: restart-airflow        
        spec:
          restartPolicy: Never
          serviceAccountName: deployment-edit-sa
          containers:
          - name: restart-airflow
            image: europe-north1-docker.pkg.dev/knada-gcp/knada-north/knada-restart-scheduler
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-edit-sa
  namespace: monitoring
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-edit-role
rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - update
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - list
      - get  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-edit-binding
subjects:
  - kind: ServiceAccount
    name: deployment-edit-sa
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: deployment-edit-role
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-server
  namespace: monitoring
spec:
  policyTypes:
  - Egress
  egress:
  - to:
    ports:
    - protocol: TCP
      port: 443  
  podSelector:
    matchLabels:
      app: restart-airflow

