resources:
- ../../base

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: europe-north1-docker.pkg.dev/knada-gcp/knada-north/knada-restart-scheduler
  newTag: b3852563535e2ee55440143282cf09db6ef9220a
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-api-server
    spec:
      egress:
        - to:
            - ipBlock:
                cidr: 100.72.0.1/32
          ports:
            - protocol: TCP
              port: 443
  target:
    kind: NetworkPolicy
    name: allow-api-server
